name: impartial
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.2.4
  - pytorch=1.10.1
  - pytorch-lightning=1.5.9
  - pyyaml=5.3
  - scikit-learn=0.23
  - scipy=1.6
  - seaborn=0.11.1
  - tensorboard=2.3.0
  - pip=21.0.1
  - torchvision=0.11.2
  - pip:
    - tensorboardx==2.2
    - torch-optimizer==0.1.0
